travis:
  secure:
    BINSTAR_TOKEN: Fw0xPiUSM2GSev37lm3UzX/3l0vhxNmSOzp3S9jlNck1qS11fhac46tOM1+OO6wfa6TPcawH4dw9Umdm0uyllyjGSQySqqJk+1M+QW385hG+viECEveKQigBnDq4z7WJUS3KZJvtfwfN8jg/PbkhLgvw+bzti4Sivwue5AdEWA/IvMQ/xosmTHLbqID9ZQSZ8sCSm9Sqogob60rmviCOqX79Pv1/kX4htHZ1sptdZc4nU+9melhcMe+gmU6E606MsdWfDV1xt5IZ8NGLUOGTHiVAx0zYfHaE6DX1nLN4djfKINMpg95Ugfg1KOAUw3g15cvc03wqYxirlo37slVcso1TBhf1CaKzt8rYi/aiLMj4tixBBWI6oVdkgnxxGifsegaGML/AZFs4cwI8tcZn40J04/fsd5oTKpgnJiQM/9o9mAAX+gD3mfRn2YVMOGD+zMTWDwgYu/X4hhHa09vSCo3yG0ANyyebAGoGv9qy0FYDsWoHGvNb5JZzvwdYKa2HNI4hu1v5xNJU8She7Cau1P8YtBUP9HZe0uiB+xW3gKJCM73y13No46CiOMxRnfQKlRNuH7tz3vZMB91YHANIfLRtgqeahX71hm+BTMQtM4RYjniDoXJqru4ZJ45NJtqxPQyPYc96XGB45MnX5ngkPzJeC47Mjez5AP/fNB2Kh2o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
